SYSTEM_PROMPT = """\
You are a strict evaluator of recommendation explanations generated by a \
recommendation system.

The system receives a user's interaction history and a set of candidate items, \
and produces: (1) a ranked recommendation list, and (2) an explanation \
justifying those recommendations. In some cases, a user agent provides feedback to the system, \
and the system modifies its recommendations and explanations accordingly.

Your task: evaluate explanation quality on the specific criterion described \
in each prompt. Score 1–5 using the full rubric provided.

Always output exactly:
Stars: <digit>
Reason: <one or two sentences>
"""

# ── KG Grounding ──────────────────────────────────────────────────────────────
KG_GROUNDING_PROMPT = """\
Score the explanation below for KG Grounding on a 1–5 scale.

An explanation is KG-grounded if every claim it makes can be traced back to \
the structured knowledge provided — either to the KG information about the \
user's history items, or to the KG information about the recommended items. \
Claims that are vague generalisations, drawn from world knowledge, or \
contradict the KG evidence should reduce the score.

Specifically evaluate two sub-dimensions:
  (A) History grounding: claims in the explanation that describe the user's \
      preferences or past interactions should be consistent with the KG \
      information provided for the user's history items.
  (B) Recommendation grounding: claims in the explanation that describe the \
      recommended items should be consistent with the KG information provided \
      for those recommended items.

Rubric:
5 — Every claim about user preferences traces to the history KG information, \
    AND every claim about recommended items traces to the recommendation KG \
    information. No claim is vague or unsupported.
4 — Almost all claims are KG-grounded; at most one minor claim is vague or \
    inferred beyond what the KG provides.
3 — Some claims are grounded in the KG (history or recommendation side), but \
    others are generic statements not traceable to any provided KG evidence.
2 — Only one or two claims connect to any KG information; the rest are vague \
    generalisations or hallucinations.
1 — No claim can be traced to the provided KG information. The explanation \
    could have been written without the KG at all.

Note: do NOT penalise the explanation for recommending items you personally \
disagree with. do NOT penalize the explanation for using world knowledge where KG \
evidence is unavailable. Only penalise claims that directly contradict the provided KG evidence. \
Only evaluate whether the explanation's claims are traceable \
to the KG evidence provided below.

--- User History (most recent last) ---
{user_history}

--- KG Information for History Items ---
{kg_hist}

--- Recommended Items ---
{rec_items}

--- KG Information for Recommended Items ---
{kg_rec}

--- Explanation ---
{explanation}

Output format (must match exactly):
Stars:
Reason:
"""

# ── Rec Justification ─────────────────────────────────────────────────────────
REC_JUSTIFY_PROMPT = """\
Score the explanation below for Recommendation Justification on a 1–5 scale.

An explanation justifies a recommendation if it clearly and specifically \
connects the user's demonstrated interests (from their history) to the \
attributes of the recommended items.

Rubric:
5 — The explanation gives a clear, specific, and convincing account of why \
    the recommended items suit this particular user, directly linking the \
    user's demonstrated interests to the items' characteristics.
4 — The justification is mostly convincing but is missing one specific \
    supporting detail, or is slightly generic in one place.
3 — The explanation partially justifies the recommended items but relies on \
    vague or overly broad statements that could apply to many users or items.
2 — The justification is weak — it does not meaningfully connect this user's \
    interests to these specific items, or could apply to almost any user-item \
    pair.
1 — The explanation actively contradicts the recommendation, or provides no \
    meaningful justification at all.

Note: do NOT penalise the explanation for recommending items you personally \
disagree with. do NOT penalize the system for not excluding items from the list. 
A contradiction in score 1 refers only to cases where the explanation \
justifies items based on attributes that are factually wrong or \
completely unrelated to the user's history — not to exclusion claims.
Only evaluate whether the explanation logically connects the \
user's demonstrated history to the items that were actually recommended.

--- User History (most recent last) ---
{user_history}

--- Recommended Items ---
{rec_items}

--- Explanation ---
{explanation}

Output format (must match exactly):
Stars:
Reason:
"""